# Das hier ist ein Template für die schnelle Installation von Openslides mit PostgreSQL und Redis 
# Bitte das POSTGRES_PASSWORD befüllen und das DJANGO_SECRET!
# Auch den Port unter Openslides befüllen ist wichtig

postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: openslides
      POSTGRES_DB: openslides
    ports:
        - "5432"

redis:
    image: redis
    restart: always

openslides:
    image: matthiasescher/openslides:${Version}
    ports:
        - "${Public_Port}:8000"
    environment:
      DJANGO_SECRET: ${DJANGO_SECRET}
      Branding: ${Branding}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM_MAIL: ${EMAIL_FROM_MAIL}
    links: 
        - "postgres-db"
        - "redis"